repository: Oppedijk/Oppedijk.github.io
encoding: utf-8

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  sailing:
    output: true
  bandg:
    output: true
#    permalink: /sailing/:path/
